services:
  runner:
    image: ghcr.io/yosemiteyss/actions-ubuntu-image:latest
    restart: unless-stopped
    volumes:
      # dind: docker socket pass through
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO=
      - TOKEN=
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '1G'
